### ISSUE TITLE
Flutter driver for iOS Real Device (Hybrid App)

### ISSUE THREAD

**Issue by hailongchen-chowbus** [appium-flutter-driver/appium-flutter-driver#145]
The server is running
[2021-02-23 07:27:36][Appium] Welcome to Appium v1.18.3
[2021-02-23 07:27:36][Appium] Non-default server args:
[2021-02-23 07:27:36][Appium]   allowCors: true
[2021-02-23 07:27:36][Appium]   logTimestamp: true
[2021-02-23 07:27:36][Appium]   localTimezone: true
[2021-02-23 07:27:36][Appium]   relaxedSecurityEnabled: true
[2021-02-23 07:27:36][Appium]   allowInsecure: {
[2021-02-23 07:27:36][Appium]   }
[2021-02-23 07:27:36][Appium]   denyInsecure: {
[2021-02-23 07:27:36][Appium]   }
[2021-02-23 07:27:36][Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[2021-02-23 07:27:36][Appium] Appium REST http interface listener started on 0.0.0.0:4723
[2021-02-23 07:27:52][HTTP] --> POST /wd/hub/session
[2021-02-23 07:27:52][HTTP] {"desiredCapabilities":{"automationName":"Flutter","bundleId":"xxxxxxx","deviceName":"iPad","platformName":"iOS","platformVersion":"13.3","retryBackoffTime":500,"startIWDP":true,"udid":"auto","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[2021-02-23 07:27:52][MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"Flutter","bundleId":"xxxxxxxxxxx","deviceName":"iPad","platformName":"iOS","platformVersion":"13.3","retryBackoffTime":500,"startIWDP":true,"udid":"auto","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[2021-02-23 07:27:52][BaseDriver] Event 'newSessionRequested' logged at 1614079672077 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][Appium] Appium v1.18.3 creating new FlutterDriver (v0.0.23) session
[2021-02-23 07:27:52][Appium] Applying relaxed security to 'FlutterDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[2021-02-23 07:27:52][BaseDriver] Creating session with MJSONWP desired capabilities: {
[2021-02-23 07:27:52][BaseDriver]   "automationName": "Flutter",
[2021-02-23 07:27:52][BaseDriver]   "bundleId": "xxxxxxxxxxxx",
[2021-02-23 07:27:52][BaseDriver]   "deviceName": "iPad",
[2021-02-23 07:27:52][BaseDriver]   "platformName": "iOS",
[2021-02-23 07:27:52][BaseDriver]   "platformVersion": "13.3",
[2021-02-23 07:27:52][BaseDriver]   "retryBackoffTime": 500,
[2021-02-23 07:27:52][BaseDriver]   "startIWDP": true,
[2021-02-23 07:27:52][BaseDriver]   "udid": "auto",
[2021-02-23 07:27:52][BaseDriver]   "newCommandTimeout": 0,
[2021-02-23 07:27:52][BaseDriver]   "connectHardwareKeyboard": true
[2021-02-23 07:27:52][BaseDriver] }
[2021-02-23 07:27:52][BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[2021-02-23 07:27:52][BaseDriver]   bundleId
[2021-02-23 07:27:52][BaseDriver]   retryBackoffTime
[2021-02-23 07:27:52][BaseDriver]   startIWDP
[2021-02-23 07:27:52][BaseDriver]   connectHardwareKeyboard
[2021-02-23 07:27:52][BaseDriver] Session created with session id: bc6cc611-c291-4385-a870-df8e9751c7ec
[2021-02-23 07:27:52][FlutterDriver] Starting an IOS proxy session
[2021-02-23 07:27:52][BaseDriver] Creating session with MJSONWP desired capabilities: {
[2021-02-23 07:27:52][BaseDriver]   "automationName": "Flutter",
[2021-02-23 07:27:52][BaseDriver]   "bundleId": "xxxxxxxxxxxx",
[2021-02-23 07:27:52][BaseDriver]   "deviceName": "iPad",
[2021-02-23 07:27:52][BaseDriver]   "platformName": "iOS",
[2021-02-23 07:27:52][BaseDriver]   "platformVersion": "13.3",
[2021-02-23 07:27:52][BaseDriver]   "retryBackoffTime": 500,
[2021-02-23 07:27:52][BaseDriver]   "startIWDP": true,
[2021-02-23 07:27:52][BaseDriver]   "udid": "auto",
[2021-02-23 07:27:52][BaseDriver]   "newCommandTimeout": 0,
[2021-02-23 07:27:52][BaseDriver]   "connectHardwareKeyboard": true
[2021-02-23 07:27:52][BaseDriver] }
[2021-02-23 07:27:52][BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[2021-02-23 07:27:52][BaseDriver]   retryBackoffTime
[2021-02-23 07:27:52][BaseDriver] Session created with session id: e7ef7f3d-0e7d-4aab-9d48-687fb9b7d328
[2021-02-23 07:27:52][XCUITest] Current user: 'hailong.chen'
[2021-02-23 07:27:52][XCUITest] Auto-detecting real device udid...
[2021-02-23 07:27:52][XCUITest] Detected real device udid: 'c5bc6919bc703e911c84e0603f17d1************'
[2021-02-23 07:27:52][XCUITest] Creating iDevice object with udid 'c5bc6919bc703e911c84e0603f17d1********'
[2021-02-23 07:27:52][XCUITest] Determining device to run tests on: udid: 'c5bc6919bc703e911c84e0603f*********, real device: true
[2021-02-23 07:27:52][BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1614079672117 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][BaseDriver] Event 'appConfigured' logged at 1614079672117 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][BaseDriver] Event 'resetStarted' logged at 1614079672117 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][XCUITest] Reset: running ios real device reset flow
[2021-02-23 07:27:52][BaseDriver] Event 'resetComplete' logged at 1614079672117 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][WebDriverAgent] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[2021-02-23 07:27:52][WebDriverAgent] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[2021-02-23 07:27:52][XCUITest] Crash reports root '/Users/hailong.chen/Library/Logs/CrashReporter/MobileDevice/ipad4.hailong' does not exist. Got nothing to gather.
[2021-02-23 07:27:52][BaseDriver] Event 'logCaptureStarted' logged at 1614079672368 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][XCUITest] Setting up real device
[2021-02-23 07:27:52][WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[2021-02-23 07:27:52][DevCon Factory] Requesting connection for device c5bc6919bc703e911c84e0603f17d1ef7222034e on local port 8100, device port 8100
[2021-02-23 07:27:52][DevCon Factory] Cached connections count: 1
[2021-02-23 07:27:52][DevCon Factory] Found cached connections on port #8100: ["c5bc6919bc703e911c84e0603f17d1ef7222034e:8100"]
[2021-02-23 07:27:52][DevCon Factory] Port #8100 is busy. Did you quit the previous driver session(s) properly?
[2021-02-23 07:27:52][DevCon Factory] Trying to release the port
[2021-02-23 07:27:52][DevCon Factory] Releasing the listener for 'c5bc6919bc703e911c84e0603f17d1ef7222034e:8100'
[2021-02-23 07:27:52][iProxy@c5bc6919:8100] Closing the connection
[2021-02-23 07:27:52][iProxy@c5bc6919:8100] The connection has been closed
[2021-02-23 07:27:52][DevCon Factory] Port #8100 has been successfully released after 1ms
[2021-02-23 07:27:52][DevCon Factory] Successfully requested the connection for c5bc6919bc703e911c84e0603f17d1ef7222034e:8100
[2021-02-23 07:27:52][XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[2021-02-23 07:27:52][WD Proxy] Matched '/status' to command name 'getStatus'
[2021-02-23 07:27:52][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[2021-02-23 07:27:52][WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.2","version":"13.3.1"},"ios":{"ip":"172.16.22.229"},"ready":true,"build":{"time":"Feb 23 2021 10:24:16","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"2A9537FF-6629-4386-AFB0-6ED9D2857AFF"}
[2021-02-23 07:27:52][WebDriverAgent] Upgrade timestamp of the currently bundled WDA: 1607503722580
[2021-02-23 07:27:52][WebDriverAgent] Upgrade timestamp of the WDA on the device: undefined
[2021-02-23 07:27:52][WebDriverAgent] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[2021-02-23 07:27:52][XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[2021-02-23 07:27:52][XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[2021-02-23 07:27:52][BaseDriver] Event 'wdaStartAttempted' logged at 1614079672643 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][WebDriverAgent] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[2021-02-23 07:27:52][WD Proxy] Matched '/status' to command name 'getStatus'
[2021-02-23 07:27:52][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[2021-02-23 07:27:52][WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.2","version":"13.3.1"},"ios":{"ip":"172.16.22.229"},"ready":true,"build":{"time":"Feb 23 2021 10:24:16","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"2A9537FF-6629-4386-AFB0-6ED9D2857AFF"}
[2021-02-23 07:27:52][BaseDriver] Event 'wdaSessionAttempted' logged at 1614079672654 (19:27:52 GMT+0800 (中国标准时间))
[2021-02-23 07:27:52][XCUITest] Sending createSession command to WDA
[2021-02-23 07:27:52][WD Proxy] Matched '/session' to command name 'createSession'
[2021-02-23 07:27:52][WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"xxxxxxxxxxxxx","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[2021-02-23 07:27:54][WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/hailong.chen/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[2021-02-23 07:27:54][WebDriverAgent] Got derived data root: '/Users/hailong.chen/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[2021-02-23 07:27:56][WD Proxy] Got response with status 200: {"value":{"sessionId":"466BA8FF-B17F-4CE8-8C76-3AC1B6911E43","capabilities":{"device":"ipad","browserName":"xxxxxxxxxxx","sdkVersion":"13.3.1","CFBundleIdentifier":"xxxxxxxxxxxx"}},"sessionId":"466BA8FF-B17F-4CE8-8C76-3AC1B6911E43"}
[2021-02-23 07:27:56][WD Proxy] Determined the downstream protocol as 'W3C'
[2021-02-23 07:27:56][BaseDriver] Event 'wdaSessionStarted' logged at 1614079676751 (19:27:56 GMT+0800 (中国标准时间))
[2021-02-23 07:27:56][BaseDriver] Event 'wdaStarted' logged at 1614079676752 (19:27:56 GMT+0800 (中国标准时间))
[2021-02-23 07:27:56][XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[2021-02-23 07:27:56][BaseDriver] Event 'orientationSet' logged at 1614079676753 (19:27:56 GMT+0800 (中国标准时间))
[2021-02-23 07:27:56][BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[2021-02-23 07:27:56][BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[2021-02-23 07:27:56][FlutterDriver] Deleting Flutter Driver session
[2021-02-23 07:27:56][BaseDriver] Event 'newSessionStarted' logged at 1614079676771 (19:27:56 GMT+0800 (中国标准时间))
[2021-02-23 07:27:56][MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[2021-02-23 07:27:56][MJSONWP]     at Object.exports.processLogToGetobservatory (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:128:9)
[2021-02-23 07:27:56][MJSONWP]     at Object.exports.getObservatoryWsUri (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:30:21)
[2021-02-23 07:27:56][MJSONWP]     at Object.exports.startIOSSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:22:28)
[2021-02-23 07:27:56][MJSONWP]     at runMicrotasks ()
[2021-02-23 07:27:56][MJSONWP]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2021-02-23 07:27:56][MJSONWP]     at FlutterDriver.exports.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[2021-02-23 07:27:56][MJSONWP]     at AppiumDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:358:35)
[2021-02-23 07:27:56][MJSONWP] Destroying socket connection
[2021-02-23 07:27:56][HTTP] <-- POST /wd/hub/session 500 4697 ms - 178
[2021-02-23 07:27:56][HTTP] 
[2021-02-23 07:27:56][HTTP] --> DELETE /wd/hub/session
[2021-02-23 07:27:56][HTTP] {}
[2021-02-23 07:27:56][HTTP] No route found. Setting content type to 'text/plain'
[2021-02-23 07:27:56][HTTP] <-- DELETE /wd/hub/session 404 6 ms - 57
[2021-02-23 07:27:56][HTTP]

**Comment by hailongchen-chowbus** [comment]
The App is hybrid. flutter embedded.

**Comment by shibupanda** [comment]
In which file enableFlutterDriverExtension() has been added?

**Comment by hailongchen-chowbus** [comment]
@shibupanda    
The following steps in Hybrid Project is set:
`dev_dependencies:
	test: any
	flutter_test:
		sdk: flutter
	flutter_driver:
		sdk: flutter`

`
void main() {
	enableFlutterDriverExtension();
	runApp(MyApp());
}
`

**Comment by shibupanda** [comment]
@hailongchen-chowbus is the file name is main.dart?

**Comment by hailongchen-chowbus** [comment]
> @hailongchen-chowbus is the file name is main.dart?

"dependencies" is configuration in pubspec.yaml file; 
"main" is in main.dart file

**Comment by KazuCocoa** [comment]
How about the latest `appium@beta`?
Please make sure your flutter-driver is 0.0.28+.

**Comment by hailongchen-chowbus** [comment]
Still error even though Appium_1.20.2, it's the same error info.
And...I've refactored the test environment, flutter-driver is the newest
@KazuCocoa 
Do your team has ios real devices, hybrid application (flutter embedded)?

**Comment by KazuCocoa** [comment]
No, i haven't tried.

Technically, flutter-driver only needs websocket to Dart VM running on a device. The URL is exposed by `enableFlutterDriverExtension`.

As debug, you can check if the iOS device's system log has a line like `Observatory listening on xxxx`. If it did not exist, this flutter driver cannot interact with the DartVM layer technically. It means this driver does not work for it.
https://github.com/truongsinh/appium-flutter-driver/blob/master/driver/lib/sessions/observatory.ts#L143

**Comment by hailongchen-chowbus** [comment]
@KazuCocoa 
actually, I've read all the issues and the communication theory about flutter driver before. 
uh.... thank your suggestion @KazuCocoa  
I'll try again.

**Comment by wenhuichen** [comment]
> The App is hybrid. flutter embedded.

我们公司也是混合app，inspector元素识别不了，你是怎么识别的？（纯flutter的app可以识别）

**Comment by KazuCocoa** [comment]
For iOS real devices, https://appium.io/docs/en/drivers/ios-xcuitest/#accessibility-preferences-fine-tuning this accessibility preference helped a couple of friends of mine. Nothing we can do except for it so far.

**Comment by hailongchen-chowbus** [comment]
@wenhuichen  你可以在iOS的设置中，将"读取屏幕"选型打开

**Comment by hailongchen-chowbus** [comment]
I show you the screenshots.

the settings contents are in file {project}/pubspec.yaml.
[image: image.png]

 `enableFlutterDriverExtension()` was added in  {project} /lib
<https://github.com/FanTuanEats/restaurant_app/tree/dev/lib>/main.dart .
But now our developers have removed the code.



shibupanda ***@***.***> 于2021年2月26日周五 上午3:00写道：

**Comment by juanduarte1927** [comment]
the automation for ios real devices is available?

**Comment by hailongchen-chowbus** [comment]
> the automation for ios real devices is available?

Not yet

**Comment by KazuCocoa** [comment]
I assume https://github.com/appium-flutter-driver/appium-flutter-driver/pull/135 https://github.com/appium-flutter-driver/appium-flutter-driver/pull/130 fixed this issue. v0.0.29.
(iOS 14+ requires profile build tho by Flutter)
