### ISSUE TITLE
Running tests on BrowserStack

### ISSUE THREAD

**Issue by neillfontes** [appium-flutter-driver/appium-flutter-driver#162]
Hi everyone,

For those that ironed out the issues in their test suites and would like to run tests on BrowserStack I worked in a demo a few days ago and the tests work well there. In order to use it, the wdio configuration is as follows:

```js
const wdio = require('webdriverio');

const osSpecificOps = process.env.APPIUM_OS === 'android' ? {
  //browserstack
  device: 'Google Pixel 4',
  os_version: '11.0',
  browserName: 'android',
  realMobile: 'true',
  app: 'bs://[application-id]',
  //appium
  retryBackoffTime: 7500,
  maxRetryCount: 3,
  noReset: false,
}: process.env.APPIUM_OS === 'ios' ? {
  //browserstack
  device: 'iPhone 12',
  os_version: '14',
  browserName: 'ios',
  realMobile: 'true',
  app: '',
  //appium
  retryBackoffTime: 7500,
  maxRetryCount: 3,
  noReset: false,
} : {};

//browserstack-specific settings
const opts = {
    protocol: 'https',
    hostname: 'hub-cloud.browserstack.com',
    port: 443,
    user: '',
    key: '',
    'browserstack.appium_version' : '1.20.2',
  capabilities: {
    ...osSpecificOps,
    automationName: 'Flutter'
  }
};
```

Few considerations:

- You will have to upload your application to their cloud in order to get the corresponding `bs://[application-id]` using their webapp or curl.

```bash
curl -u "user:key" \
-X POST "https://api-cloud.browserstack.com/app-automate/upload" \
-F "file=@/path/to/your.apk"
```

- You will have to pin the Appium version to 1.20.2 for the time being.
- You will need your own user and key to access their cloud

More details can be found [here](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/select-automation-engine) and [here](https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps).

I have tried SauceLabs as well but the Appium commands don't get injected because the driver seems to be missing there. The app only gets launched and nothing else happens. I would like to check AWS Device Farm as well but so far from the documentation I've read I couldn't find anything so far related to Flutter support.

**Comment by cuk2dn95** [comment]
thanks your post, I also got the problem with driver on SauceLabs

**Comment by teeencho** [comment]
Thank you for sharing this !! Were you able to run on iOS real devices? how?

**Comment by KazuCocoa** [comment]
This situation might change in some cloud vendors.

e.g. flutter driver 0.0.29 (appium 1.21+) on HeadSpin allows flutter apps with this appium-flutter-driver.
(iOS needs to be profile build tho for iOS 14+)

**Comment by slover422** [comment]
The configuration works for android perfectly, but for ios it return(Request failed with status 404 due to Driver is not ready , cannot execute execute)after my first flutter:checkHealth execute request. And the ipa also compiled in profile mode.

Who can help please...

**Comment by drkhannah** [comment]
browserstack has told me that i need to build my ios app in --profile mode, which is also true of your documentation

the problem is that even if i build in --profile mode, they only way i can archive a .ipa is to choose the Release scheme, choosing any other scheme causes the archive to fail.

running this command to build in profile mode makes the build succeed

[08:09:30]: $ flutter build ios --profile --build-number\=776 --build-name\=5.0.776 --no-codesign --flavor Profile -t lib/test_main.dart

then i archive the .ipa using the xcode Release scheme, the archive succeeds.

I upload to browserstack app live

then i run my appium tests but i get this error

[0-0] 2022-02-22T13:17:27.447Z INFO webdriver: Retrying 3/3
[0-0] 2022-02-22T13:17:27.447Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session
[0-0] 2022-02-22T13:17:27.448Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       app: 'REDACTED',
[0-0]       device: 'iPhone 12',
[0-0]       os_version: '14.0',
[0-0]       project: 'Baird Mobile',
[0-0]       build: 'browserstack-build-ios',
[0-0]       name: 'Tests',
[0-0]       automationName: 'Flutter',
[0-0]       acceptSslCerts: 'true'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     app: 'REDACTED',
[0-0]     device: 'iPhone 12',
[0-0]     os_version: '14.0',
[0-0]     project: 'Baird Mobile',
[0-0]     build: 'browserstack-build-ios',
[0-0]     name: 'Tests',
[0-0]     automationName: 'Flutter',
[0-0]     acceptSslCerts: 'true'
[0-0]   }
[0-0] }
[0-0] 2022-02-22T13:18:35.834Z ERROR webdriver: Request failed with status 200 due to WebDriver Error: Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0] 2022-02-22T13:18:35.834Z ERROR webdriver: WebDriver Error: Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0]     at getErrorFromResponseBody (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:197:12)
[0-0]     at NodeJSRequest._request (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/request/index.js:158:60)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async startWebDriverSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:67:20)
[0-0]     at async Function.newSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/index.js:58:45)
[0-0]     at async remote (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriverio/build/index.js:73:22)
[0-0]     at async Runner._startSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2022-02-22T13:18:35.835Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0]     at startWebDriverSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:72:15)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async Function.newSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/index.js:58:45)
[0-0]     at async remote (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriverio/build/index.js:73:22)
[0-0]     at async Runner._startSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] FAILED in joshuarufer_jXfqM5/BairdMobile - /src/specs/login_tests.js
2022-02-22T13:18:35.948Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:03:58 

2022-02-22T13:18:35.950Z INFO @wdio/local-runner: Shutting down spawned worker
2022-02-22T13:18:36.202Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-02-22T13:18:36.203Z INFO @wdio/local-runner: shutting down

**Comment by drkhannah** [comment]
the appium settings posted above in the first comment don't work for me either
